# Generated by Django 5.0 on 2023-12-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='editor_text',
            field=models.TextField(null=True),
        ),
    ]
